export const ACHIEVEMENTS_LIST = [
  {
    id: 'lara',
    title: 'Tomb Raider III',
    description: 'Desbloquea a Lara',
    unlocked: false,
    rarity: 'legendary',
    date: '12 May, 2025',
    svgIcon: `lara.png`,
  },
  {
    id: 'link',
    title: 'Encontrarás a Zelda?',
    description: 'Desbloquea a Link',
    unlocked: false,
    rarity: 'legendary',
    date: '12 May, 2025',
    svgIcon: `link.png`,
  },
  {
    id: 'legolas',
    title: 'Señor de los arqueros',
    description: 'Desbloquea a Legolas',
    unlocked: false,
    rarity: 'legendary',
    date: '12 May, 2025',
    svgIcon: `legolas.png`,
  },
  {
    id: 'collect_dragonballs',
    title: 'Mejor que una lampara',
    description: 'Has recogido 7 bolas de cristal, que extrañas...',
    unlocked: false,
    rarity: 'legendary',
    date: '12 May, 2025',
    svgIcon: `dragonball.png`,
  },
  {
    id: 'kill_wumpus',
    title: 'Has matado al bisho malo',
    description: 'Eliminaste a un Wumpus con una flecha bien dirigida',
    unlocked: false,
    rarity: 'uncommon',
    date: '12 May, 2025',
    svgIcon: `kill_wumpus.svg`,
  },
  {
    id: 'collect_heart',
    title: 'Como nuevo',
    description: 'Encontrar vidas siempre es un alivio',
    unlocked: false,
    rarity: 'uncommon',
    date: '12 May, 2025',
    svgIcon: `heart.svg`,
  },
  {
    id: 'escape_rat',
    title: 'Has escapado como una rata',
    description: 'Escapaste de la cueva sin matar a ningún Wumpus',
    unlocked: false,
    rarity: 'common',
    date: '10 May, 2025',
    svgIcon: `escape_rat.svg`,
  },
  {
    id: 'collect_arrow',
    title: 'Has recogido una flecha caída',
    description: 'Encontraste una flecha adicional durante tu aventura',
    unlocked: false,
    rarity: 'uncommon',
    svgIcon: `collect_arrow.svg`,
  },
  {
    id: 'hero_escape',
    title: 'Héroe: escapaste matando al bisho malo',
    description: 'Mataste al Wumpus y escapaste con el oro',
    unlocked: false,
    rarity: 'epic',
    date: '11 May, 2025',
    svgIcon: `hero_escape.svg`,
  },
  {
    id: 'survive_blackout',
    title: 'Has vivido un apagón',
    description: 'Experimentaste un apagón! Vaya ni que estuvieses en ESPAÑA',
    unlocked: false,
    rarity: 'rare',
    svgIcon: `survive_blackout.svg`,
  },
  {
    id: 'survive_blackout_complete',
    title: 'Has sobrevivido a un apagón',
    description: 'Sobreviviste a un apagón y continuaste tu aventura',
    unlocked: false,
    rarity: 'legendary',
    svgIcon: `survive_blackout_complete.svg`,
  },
  {
    id: 'death_by_wumpus',
    title: 'Muerte por bisho malo',
    description: 'Fuiste devorado por un Wumpus',
    unlocked: false,
    rarity: 'common',
    date: '9 May, 2025',
    svgIcon: `death_by_wumpus.svg`,
  },
  {
    id: 'death_by_pit',
    title: 'Te ahogaste en un pozito',
    description: 'Caíste en un pozo y no pudiste salir',
    unlocked: false,
    rarity: 'common',
    date: '8 May, 2025',
    svgIcon: `death_by_pit.svg`,
  },
  {
    id: 'collect_gold',
    title: 'Has recogido moneda',
    description: 'Encontraste el oro en la cueva',
    unlocked: false,
    rarity: 'uncommon',
    date: '11 May, 2025',
    svgIcon: `collect_gold.svg`,
  },
  {
    id: 'death_during_blackout',
    title: 'Muerte durante el apagón',
    description: 'Fuiste víctima de la oscuridad durante un apagón',
    unlocked: false,
    rarity: 'rare',
    date: '13 May, 2025',
    svgIcon: `death_during_blackout.svg`,
  },
  {
    id: 'hard_head',
    title: 'Cabeza dura',
    description: 'Has chocado contra muros repetidamente',
    unlocked: false,
    rarity: 'common',
    svgIcon: `hard_head.svg`,
  },
  {
    id: 'large_map_completion',
    title: 'Explorador de grandes cavernas',
    description: 'Completaste un mapa de más de 12x12',
    unlocked: false,
    rarity: 'epic',
    date: '14 May, 2025',
    svgIcon: `large_map_completion.svg`,
  },
  {
    id: 'missed_last_arrow',
    title: 'Fallaste tu última bala',
    description: 'Disparaste tu última flecha y fallaste el tiro',
    unlocked: false,
    rarity: 'common',
    date: '10 May, 2025',
    svgIcon: `missed_last_arrow.svg`,
  },
  {
    id: 'wasted_arrows',
    title: 'Desastre',
    description: 'Acabaste la partida con más de una bala y no mataste al bicho',
    unlocked: false,
    rarity: 'uncommon',
    svgIcon: `wasted_arrows.svg`,
  },
  {
    id: 'speedrunner',
    title: 'Speedrunner',
    description: 'Completaste una partida en menos de 10 segundos',
    unlocked: false,
    rarity: 'legendary',
    svgIcon: `speedrunner.svg`,
  },
  {
    id: 'true_gamer',
    title: 'True Gamer',
    description: 'Eres un OG WASD son tus keys',
    unlocked: false,
    rarity: 'common',
    svgIcon: `true_gamer.svg`,
  },
  {
    id: 'sniper',
    title: 'Francotirador',
    description: 'Mataste al Wumpus con un disparo desde más de 5 casillas de distancia',
    unlocked: false,
    rarity: 'epic',
    svgIcon: `sniper.svg`,
  },
  {
    id: 'death_duel',
    title: 'Duelo a Muerte',
    description: 'Mataste al Wumpus estando en una casilla adyacente',
    unlocked: false,
    rarity: 'legendary',
    svgIcon: `death_duel.svg`,
  },
  {
    id: 'novice_cartographer',
    title: 'Cartógrafo Novato',
    description: 'Exploraste el 50% de una cueva',
    unlocked: false,
    rarity: 'common',
    svgIcon: `novice_cartographer.svg`,
  },
  {
    id: 'expert_cartographer',
    title: 'Cartógrafo Experto',
    description: 'Exploraste el 100% de una cueva',
    unlocked: false,
    rarity: 'legendary',
    svgIcon: `expert_cartographer.svg`,
  },
  {
    id: 'blind_shot',
    title: 'Disparo a Ciegas',
    description: 'Mataste al Wumpus durante un apagón',
    unlocked: false,
    rarity: 'epic',
    svgIcon: `blind_shot.svg`,
  },
  {
    id: 'last_breath',
    title: 'Último Aliento',
    description: 'Mataste al Wumpus y moriste en el intento',
    unlocked: false,
    rarity: 'rare',
    svgIcon: `last_breath.svg`,
  },
  {
    id: 'pentakill',
    title: 'Pentakill',
    description: 'Has matado a 5 enemigos seguidos',
    unlocked: false,
    rarity: 'legendary',
    svgIcon: `penta.png`,
  },
  {
    id: 'secret',
    title: 'Secreto oculto 8x8',
    description: 'Encontraste al Jedi, que la fuerza te acompañe!',
    unlocked: false,
    rarity: 'legendary',
    hidden: true,
    svgIcon: `secret.svg`,
  },
  {
    id: 'completionist',
    title: 'Coleccionista',
    description: 'Has ganado una partida teniendo todos los logros del juego. ¡Eres una leyenda!',
    unlocked: false,
    rarity: 'legendary',
    svgIcon: `completionist.svg`,
  },
];
