sonar.projectKey=chdelucia_hunt-the-bishomalo
sonar.organization=chdelucia


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=hunt-the-bishomalo
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src,libs
sonar.exclusions=**/node_modules/**,**/.vscode/**,**/dist/**,**/*.config.ts,**/main.ts,**/*routes.ts,**/*test-setup.ts,**/*.const.ts,src/app/utils/transloco-loader.ts
sonar.coverage.exclusions=**/*.stories.ts,**/*.interface.ts,**/*.model.ts

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.tests=src,libs
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/hunt-the-bishomalo/lcov.info,\
coverage/libs/config/feature/lcov.info,\
coverage/libs/instructions/feature/lcov.info,\
coverage/libs/achievements/feature/lcov.info,\
coverage/libs/achievements/data-access/lcov.info,\
coverage/libs/achievements/ui/lcov.info,\
coverage/libs/shop/feature/lcov.info,\
coverage/libs/gamestats/feature/lcov.info,\
coverage/libs/gamestats/data-access/lcov.info,\
coverage/libs/core/data-access/lcov.info,\
coverage/libs/game/feature/lcov.info,\
coverage/libs/game/data-access/lcov.info,\
coverage/libs/game/ui/lcov.info,\
coverage/libs/story/feature/lcov.info,\
coverage/libs/shared/data/lcov.info,\
coverage/libs/shared/ui/lcov.info,\
coverage/libs/shared/util/lcov.info,\
coverage/libs/credits/feature/lcov.info,\
coverage/libs/boss/feature/lcov.info,\
coverage/libs/chars/feature/lcov.info
