import { ChangeDetectionStrategy, Component, inject, isDevMode, signal } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { TranslocoModule } from '@jsverse/transloco';
import { GAME_SOUND_TOKEN, GAME_STORE_TOKEN } from '@hunt-the-bishomalo/core/api';
import { GAME_ENGINE_TOKEN } from '@hunt-the-bishomalo/game/api';
import {
  form,
  FormField,
  submit,
  required,
  maxLength,
  pattern,
  min,
  max,
} from '@angular/forms/signals';
import {
  ASSETS_BASE_URL,
  Chars,
  DIFFICULTY_CONFIGS,
  DifficultyTypes,
  GameDificulty,
  GameSound,
  RouteTypes,
} from '@hunt-the-bishomalo/shared-data';
import { Router } from '@angular/router';

@Component({
  selector: 'lib-game-config',
  standalone: true,
  imports: [NgOptimizedImage, TranslocoModule, FormField],
  templateUrl: './game-config.component.html',
  styleUrls: ['./game-config.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GameConfigComponent {
  protected readonly ASSETS_BASE_URL = ASSETS_BASE_URL;
  readonly gameStore = inject(GAME_STORE_TOKEN);
  private readonly gameEngine = inject(GAME_ENGINE_TOKEN);
  private readonly gameSound = inject(GAME_SOUND_TOKEN);
  private readonly router = inject(Router);

  isDevMode = isDevMode();
  readonly configs = DIFFICULTY_CONFIGS as Record<string, GameDificulty>;

  model = signal({
    player: 'Kukuxumushu',
    size: 1,
    selectedChar: Chars.DEFAULT as Chars,
    difficulty: DifficultyTypes.EASY as DifficultyTypes,
  });

  configForm = form(this.model, (s) => {
    required(s.player);
    maxLength(s.player, 20);
    pattern(s.player, /^[a-zA-Z0-9\s\-_]*$/);

    required(s.size);
    min(s.size, 1);
    max(s.size, 20);

    required(s.selectedChar);
    required(s.difficulty);
  });

  submitForm(): void {
    submit(this.configForm, async () => {
      const { difficulty, size, player, selectedChar } = this.model();
      const difficultyConfig = DIFFICULTY_CONFIGS[difficulty];

      this.gameStore.updateGame({
        settings: {
          player,
          selectedChar,
          size: size + 3,
          blackout: false,
          difficulty: difficultyConfig,
          startTime: new Date().toISOString(),
          pits: 0, // Will be generated by engine
          arrows: 0, // Will be generated by engine
          wumpus: 0, // Will be generated by engine
          soundEnabled: this.gameStore.soundEnabled(),
        },
        lives: difficultyConfig.maxLives,
      });

      this.gameEngine.initGame();
      this.goToStory();
    });
  }

  goToStory(): void {
    this.router.navigate([RouteTypes.STORY], {
      state: { fromSecretPath: true },
    });
  }

  selectChar(char: Chars): void {
    const matchingSound: GameSound = GameSound[char.toUpperCase() as keyof typeof GameSound];
    this.model.update((m) => ({ ...m, selectedChar: char }));
    this.gameSound.stop();
    this.gameSound.playSound(matchingSound, false);
  }
}
